apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: hhnguyen255/gittix-expiration
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 256Mi
              cpu: '0.2'
          env:
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: gittix
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_ISSUER
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_AUDIENCE
            - name: JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_EXPIRATION_TIME
